{{- if .Values.ingress.enabled -}}
{{- $fullName := include "babyvelo-base.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "babyvelo-base.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if .Values.ingress.tls }}
    cert-manager.io/cluster-issuer: cloudflare
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
      - {{ .host | quote }}
      {{- end }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
