{{- $name := $.Release.Name -}}
{{- range .Values.storage }}
{{- if hasKey . "nfs"  }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .size | default "10Gi" | quote }}
---
{{- end -}}
{{- end -}}
