{{- $name := $.Release.Name -}}
{{- range .Values.storage }}
{{- if hasKey . "nfs"  }}
{{- else }}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $.Release.Name }}-{{ .name }}
    labels: 
      volumeName: {{ $.Release.Name }}-{{ .name }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /storage/{{ $.Release.Name }}-{{ .name }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bluey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels: 
      volumeName: {{ $.Release.Name }}-{{ .name }}
---
{{- end -}}
{{- end -}}
