apiVersion: v1
kind: Service
metadata:
  name: {{ include "babyvelo-base.fullname" . }}
  labels:
    {{- include "babyvelo-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "babyvelo-base.selectorLabels" . | nindent 4 }}
