apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      hosts:
        - loki.babyvelociraptor.com
    write:
      replicas: 1
    read:
      replicas: 1