apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - loki.babyvelociraptor.com
    write:
      replicas: 2
    read:
      replicas: 1