apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  values:
    container_runtime: nginx
    agent:
      # To specify each pod you want to process it logs (pods present in the node)
      acquisition:
        # The namespace where the pod is located
        - namespace: ingress-nginx-external
          # The pod name
          podName: ingress-nginx-controller-*
          # as in crowdsec configuration, we need to specify the program name so the parser will match and parse logs
          program: nginx
      # Those are ENV variables
      env:
      # As it's a test, we don't want to share signals with CrowdSec so disable the Online API.
      - name: DISABLE_ONLINE_API
        value: "true"
      # As we are running Nginx, we want to install the Nginx collection
      - name: COLLECTIONS
        value: "crowdsecurity/nginx"
    lapi:
      env:
        # As it's a test, we don't want to share signals with CrowdSec, so disable the Online API.
        - name: DISABLE_ONLINE_API
          value: "true"