apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-iii-secrets
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: db_password
    remoteRef:
      key: postgresql-auth-bluey
      property: postgres-password
  - secretKey: app_key
    remoteRef:
      key: firefly-iii-bluey
      property: app_key