apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libreddit
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - ingress-external.yaml
  - external-auth.yaml
