apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ../base
  - namespace.yaml
  - secret-cloudflare.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: external-dns
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --provider=cloudflare
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --domain-filter=babyvelociraptor.com
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --txt-owner-id=bluey
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --annotation-filter=nginx.ingress.kubernetes.io/auth-url notin ("https://auth.babyvelociraptor.com/api/verify")

patchesStrategicMerge:
 - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-dns
    spec:
      template:
        spec:
          containers:
            - name: external-dns
              env:
                - name: CF_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-api-key
                      key: CF_API_TOKEN
                      optional: false