apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: CF_API_KEY
    remoteRef:
      key: cloudflare-api-key-babyvelociraptor
      property: CF_API_KEY
  - secretKey: CF_API_EMAIL
    remoteRef:
      key: cloudflare-api-key-babyvelociraptor
      property: CF_API_EMAIL