apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.18.0

resources:
  - deployment.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml