apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-auth
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: backblaze-velero
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: backblaze-velero
      property: aws_secret_access_key
