apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: velero
  namespace: flux-system
spec:
  url: https://vmware-tanzu.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  targetNamespace: velero
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system