apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - secret-webhook.yaml
  - ../base
  - info-github-and-kustomize.yaml
# generatorOptions:
#   disableNameSuffixHash: true
# secretGenerator:
# - name: discord-webhook
#   files:
#   - address=discord-webhook.encrypted