apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: address
    remoteRef:
      key: discord-webhook
      property: address
