apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor: 
          enabled: true
      service:
        externalTrafficPolicy: Local
