apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: flux-system
spec:
  values:
    image:
      repository: actualbudget/actual-server
      tag: 24.2.0-alpine
    service:
      ports:
        - 5006
    #name is prepended with `<Chartname>-`
    storage: 
      - name: "data"
        mountPath: "/data"
    ingress:
      enabled: true
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
      hosts:
        - host: actualbudget.babyvelociraptor.com
          paths:
            - path: /
              pathType: Prefix
