---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
spec:
  selector:
    matchLabels:
      app: duckdns
  template:
    metadata:
      labels:
        app: duckdns
    spec:
      containers:
      - image: linuxserver/duckdns:version-63bf4c1a
        imagePullPolicy: IfNotPresent
        name: duckdns
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: duckdns-token
                key: TOKEN
                optional: false
          - name: SUBDOMAINS
            valueFrom:
              secretKeyRef:
                name: duckdns-token
                key: SUBDOMAINS
                optional: false
      restartPolicy: Always
