apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: duckdns-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: TOKEN
    remoteRef:
      key: duckdns-token
      property: TOKEN
  - secretKey: SUBDOMAINS
    remoteRef:
      key: duckdns-token
      property: SUBDOMAINS
