apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base-helm  # Chart already exists from bluey-internal
  - helmrelease.yaml
  - namespace.yaml
patchesStrategicMerge:
  - values.yaml