apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-external
resources:
  - ../base-1.5.1

patches:
  - path: service-patch.json
    target:
      version: v1
      kind: Service
      name: ingress-nginx-controller
  - path: ingressClass-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: IngressClass
      name: nginx

# patchesStrategicMerge:
#   - service.yaml