apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-external
resources:
  - ../base-1.5.1

patchesStrategicMerge:
  - configmap.yaml

patches:
  - path: service-patch.json
    target:
      version: v1
      kind: Service
      name: ingress-nginx-controller
  - path: ingressClass-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: IngressClass
      name: nginx
  - path: deployment-patch.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller

patchesJSON6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: ingress-nginx
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-external
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: ingress-nginx-admission
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-admission-external
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: ingress-nginx
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-external
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: ingress-nginx-admission
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-admission-external