apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: flux-system
spec:
  values:
    fullNameOverride: ingress-nginx-external
    nameOverride: ingress-nginx-external
    controller:
      metrics:
        enabled: true
        serviceMonitor: 
          enabled: true
      config:
          use-forwarded-headers: "true"
          compute-full-forwarded-for: "true"
          enable-real-ip: "true"
          # https://github.com/kubernetes/ingress-nginx/issues/5970
      ingressClassResource:
        name: nginx-external
        controllerValue: k8s.io/ingress-nginx-external
      ingressClass: nginx-external
      service:
        externalTrafficPolicy: Local
          ports:
            http: 8080
            https: 8443