apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgresql.yaml
  - pv.yaml
  - pvc.yaml
  - secret-postgresql.yaml
patchesStrategicMerge:
  - values.yaml