apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-auth
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: postgresql-auth-bluey
      property: postgres-password
