apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    global:
      postgresql:
        auth:
          database: bluey
          existingSecret: postgresql-auth
    primary:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local	
      persistence:
        existingClaim: "postgresql-data"
