apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /storage/sabnzbd-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bluey
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: media
# spec:
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadOnlyMany
#   storageClassName: nfs-ro
#   nfs:
#     server: bob.babyvelociraptor.com
#     path: "/Media"
#   mountOptions:
#     - nfsvers=4