---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadrians-wall
spec:
  selector:
    matchLabels:
      app: hadrians-wall
  template:
    metadata:
      labels:
        app: hadrians-wall
    spec:
      containers:
      - image: docker.io/babyraptor/hw-solo:e62bce8
        imagePullPolicy: IfNotPresent
        name: hadrians-wall
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always

