apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: auth
    remoteRef:
      key: external-htaccess
      property: htaccess
