# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: prometheus
#   namespace: prometheus
# spec:
#   rules:
#     - host: prometheus.babyvelociraptor.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: jellyfin
#                 port:
#                   name: web