apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - rbac.yaml
  - pv.yaml
  - prometheus.yaml
  - ingress-prometheus.yaml
  - kubelet-service-monitor.yaml