apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cyberchef-helm
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: k8s-manifests
  path: ./apps/cyberchef/bluey-helm
  prune: true
