apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cert-manager.yaml # Current as of 2022/03/13
patchesStrategicMerge:
  - leader-election-namespace.yaml # Overriding from `kube-system`