apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: "cert-manager"
spec:
  template:
    spec:
      containers:
        - name: cert-manager
          args:
          - --v=2
          - --leader-election-namespace=cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: "cert-manager"
spec:
  template:
    spec:
      containers:
        - name: cert-manager
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=cert-manager
          - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.11.0
          - --max-concurrent-challenges=60