apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: signoz
  namespace: flux-system
spec:
  values:
    global:
      storageClass: longhorn
    frontend:
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: signoz.babyvelociraptor.com
            paths:
              - path: /
                pathType: ImplementationSpecific
                port: 3301
    alertmanager:
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: alertmangler.babyvelociraptor.com
            paths:
              - path: /
                pathType: ImplementationSpecific
                port: 9093
