apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  values:
    image:
      repository: louislam/uptime-kuma 
      tag: 2.2.1
    service:
      ports:
        - 3001
    #name is prepended with `<Chartname>-`
    storage: 
      - name: "data"
        mountPath: "/app/data"
    ingress:
      enabled: true
      className: haproxy-ingress
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
      tls:
        - hosts:
          - uptime-kuma.babyvelociraptor.com
      hosts:
        - host: uptime-kuma.babyvelociraptor.com
          paths:
            - path: /
              pathType: Prefix