apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - chartmuseum.yaml
  - blueycharts-helmrepo.yaml # The URL for this ChartMuseum as a Helm Repo
  - pv.yaml
  - pvc.yaml
patchesStrategicMerge:
  - values.yaml