apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum-data
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
