apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evan-dexcom-login
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bluey
  target:
    creationPolicy: Owner
  data:
  - secretKey: DEXCOM_USERNAME
    remoteRef:
      key: evan-dexcom-client-login
      property: USERNAME
  - secretKey: DEXCOM_PASSWORD
    remoteRef:
      key: evan-dexcom-client-login
      property: PASSWORD