---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
      - image: adguard/adguardhome:latest
        imagePullPolicy: IfNotPresent
        name: adguard
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/adguardhome/work
          name: adguard-work
        - mountPath: opt/adguardhome/conf
          name: adguard-config
      restartPolicy: Always
      volumes:
      - name: adguard-work
        persistentVolumeClaim:
          claimName: adguard-work
      - name: adguard-config
        persistentVolumeClaim:
          claimName: adguard-config