---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  name: adguard
spec:
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: adguard
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  name: adguard-dns
spec:
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: adguard
  type: LoadBalancer