# Default values for babyvelo-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# env:
#   - name: DEMO_GREETING
#     value: "Hello from the environment"

# arguments: ['--arg3', 'value3', '--arg2', 'value2']


nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports: 
    - 80

ingress:
  enabled: false
  tls: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix


# Storage
# name is prepended with `<Chartname>-`
# storage: 
#   - name: "config"
#     mountPath: "/config"
#     size: "10Gi"
#   - name: "data"
#     mountPath: "/data"
#     nfs:
#       server: 192.168.1.1
#       path: /Media/Books

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
