---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma
spec:
  ports:
  - name: web
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: uptime-kuma
  type: ClusterIP