apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cyberchef-helm
  namespace: flux-system
spec:
  targetNamespace: cyberchef
  interval: 5m
  chart:
    spec:
      chart: babyvelo-base
      sourceRef:
        kind: HelmRepository
        name: blueycharts
        namespace: flux-system