---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cyberchef
  name: cyberchef
spec:
  ports:
  - name: web
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cyberchef
  type: ClusterIP