kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: radarr
  namespace: radarr
spec:
  ingressClassName: nginx
  rules:
    - host: radarr.babyvelociraptor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  name: web