apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appName vikunja-api
  namespace: flux-system
spec:
  targetNamespace: vikunja
  releaseName: *appName
  interval: 5m
  chart:
    spec:
      chart: babyvelo-base
      version: 0.3.11
      sourceRef:
        kind: HelmRepository
        name: blueycharts
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appName vikunja-frontend
  namespace: flux-system
spec:
  targetNamespace: vikunja
  releaseName: *appName
  interval: 5m
  chart:
    spec:
      chart: babyvelo-base
      version: 0.3.11
      sourceRef:
        kind: HelmRepository
        name: blueycharts
        namespace: flux-system