apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: 1password-connect
  sourceRef:
    kind: GitRepository
    name: k8s-manifests
  path: ./cluster-services/external-secrets/bluey
  prune: true
