# Deploy fluxcd from flux
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: k8s-manifests
  path: ./cluster-services/fluxcd/bluey
  prune: true
---
# Deploy all the apps in clusters/bluey
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8s-manifests
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/bluey"
  sourceRef:
    kind: GitRepository
    name: k8s-manifests
  prune: true
