# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: ingress-nginx
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   sourceRef:
#     kind: GitRepository
#     name: k8s-manifests
#   path: ./cluster-services/ingress-nginx/bluey-internal
#   prune: true
