---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  releaseName: node-exporter
  interval: 10m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
