---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qdrant
  namespace: flux-system
spec:
  releaseName: qdrant
  interval: 10m
  targetNamespace: qdrant
  chart:
    spec:
      chart: qdrant
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
  values:
    ingress:
      enabled: true
      hosts:
        - host: qdrant.babyvelociraptor.com
          paths:
            - path: /
              pathType: Prefix
              servicePort: 6333
