kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jellyfin
  namespace: dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: jellyfin
spec:
  rules:
    - host: jellyfin.babyvelociraptor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  name: web