apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  namespaceSelector:
    matchNames:
      - jellyfin
    # Missing a metrics path...