apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-operator-system
namePrefix: grafana-operator-

resources:
- namespace.yaml
- crds.yaml # https://github.com/grafana-operator/grafana-operator/tree/master/deploy/manifests/v4.8.0
- deployment.yaml
- rbac.yaml